// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const isSupabaseConfigured = !!SUPABASE_URL && !!SUPABASE_PUBLISHABLE_KEY;

// Use a placeholder URL when unconfigured so createClient() doesn't throw at
// import time. All api.ts methods check isConfigured() and return early;
// OpsProvider shows EnvErrorPage if not configured.
const safeUrl = SUPABASE_URL || 'http://localhost:0';
const safeKey = SUPABASE_PUBLISHABLE_KEY || 'unconfigured';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(safeUrl, safeKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});