// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read the Supabase URL and key from whichever env var the host provides.
// Lovable Cloud / connected Supabase → SUPABASE_URL + SUPABASE_ANON_KEY
// (no VITE_ prefix, reserved and auto-populated by Lovable).
// Plain Vite / external repo → VITE_SUPABASE_URL + VITE_SUPABASE_PUBLISHABLE_KEY
// (or the older VITE_SUPABASE_ANON_KEY name for backward compat).
const env = import.meta.env as Record<string, string | undefined>;
const SUPABASE_URL =
  env.VITE_SUPABASE_URL || env.SUPABASE_URL || '';
const SUPABASE_KEY =
  env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  env.VITE_SUPABASE_ANON_KEY ||
  env.SUPABASE_ANON_KEY ||
  env.SUPABASE_PUBLISHABLE_KEY ||
  '';

export const isSupabaseConfigured = !!SUPABASE_URL && !!SUPABASE_KEY;

const safeUrl = SUPABASE_URL || 'http://localhost:0';
const safeKey = SUPABASE_KEY || 'unconfigured';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(safeUrl, safeKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});